---
# Source: scoringmp/templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  #TODO Add default name overrides?
  name: kcontainer-scoringmp
  labels:
    chart: 'scoringmp-1.0.0'
spec:
  path: /
  to:
    kind: Service
    name: "scoringmp-service"
    weight: 100
  port:
    targetPort: http
