apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-command-ms
spec:
  template:
    spec:
      containers:
      - name: ordercommandms
        volumeMounts:
          - mountPath: /config/resources/security/es-ssl
            name: es-truststore-volume
