---
# Source: orderqueryms/templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  #TODO Add default name overrides?
  name: kcontainer-order-query
  labels:
    chart: 'orderqueryms-1.0.0'
    app.kubernetes.io/part-of: refarch-kc
spec:
  path: /
  to:
    kind: Service
    name: "order-query-ms"
    weight: 100
  port:
    targetPort: http
