apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-container-ms
spec:
  template:
    spec:
      containers:
      - name: springcontainerms
        volumeMounts:
          # Temporarily mount postgres cert in 2 locations, as the home directory differs
          # depending on the userid executing the container (OCP vs vanilla k8s)
          - mountPath: /.postgresql
            name: postgresql-ca-volume
          - mountPath: /root/.postgresql
            name: postgresql-ca-volume
