apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-command-ms
spec:
  template:
    spec:
      containers:
      - name: ordercommandms
        env:
          - name: KAFKA_APIKEY
            valueFrom:
              secretKeyRef:
                name: "eventstreams-apikey"
                key: binding
