---
# Source: kc-ui/templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  #TODO Add default name overrides?
  name: kcontainer-ui
  labels:
    chart: 'kc-ui-1.0.0'
    app.kubernetes.io/part-of: refarch-kc
spec:
  path: /
  to:
    kind: Service
    name: "kc-ui"
    weight: 100
  port:
    targetPort: http
