---
# Source: kc-ui/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "kc-ui"
  labels:
    chart: "kc-ui-1.0.0"
    app.kubernetes.io/part-of: refarch-kc
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 3010
    nodePort: 31010
  selector:
    app: "kc-ui-selector"
