apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-container-ms
spec:
  template:
    spec:
      containers:
      - name: springcontainerms
        env:
          - name: KAFKA_APIKEY
            valueFrom:
              secretKeyRef:
                name: "eventstreams-apikey"
                key: binding
          - name: POSTGRESQL_CA_PEM
            valueFrom:
              secretKeyRef:
                name: "postgresql-ca-pem"
                key: binding
          - name: TRUSTSTORE_ENABLED
            value: "true"
          - name: TRUSTSTORE_PWD
            valueFrom:
              secretKeyRef:
                name: es-truststore-jks
                key: password
          - name: TRUSTSTORE_PATH
            value: /config/resources/security/es-ssl/es-cert.jks
