apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-container-ms
spec:
  template:
    spec:
      volumes:
      - name: es-truststore-volume
        secret:
          secretName: es-truststore-jks
