---
# Source: kcontainer-reefer-simulator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-kcontainer-reefer-simulator
  labels:
    app.kubernetes.io/name: kcontainer-reefer-simulator
    helm.sh/chart: kcontainer-reefer-simulator-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kcontainer-reefer-simulator
    app.kubernetes.io/instance: release-name
