---
# Source: springcontainerms/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "springcontainerms-deployment"
  labels:
    chart: 'springcontainerms-1.0.0'
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: "springcontainerms-selector"
        version: "current"
    spec:
      serviceAccountName: reefer-simulator
      containers:
      - name: "springcontainerms"
        image: "ibmcase/kcontainer-spring-container-ms:0.1.21"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
        resources:
          requests:
            cpu: "200m"
            memory: "300Mi"
        env:
          - name: PORT
            value: "8080"
          - name: APPLICATION_NAME
            value: "springcontainerms"
          - name: TRUSTSTORE_ENABLED
            value: "true"
          - name: TRUSTSTORE_PWD
            value: "changeit"
          - name: TRUSTSTORE_PATH
            value: "/config/resources/security/es-ssl/es-cert.jks"
          #- name: JKS_LOCATION
          #  value: "$JAVA_HOME/jre/lib/security/cacerts"
          - name: KAFKA_BROKERS
            valueFrom:
              configMapKeyRef:
                name: "kafka-brokers"
                key: brokers
          - name: BPM_ANOMALY
            valueFrom:
              configMapKeyRef:
                name: "bpm-anomaly"
                key: url
                optional: true
          - name: BPM_ANOMALY_LOGIN
            valueFrom:
              configMapKeyRef:
                name: "bpm-anomaly"
                key: login
                optional: true
          - name: BPM_ANOMALY_USER
            valueFrom:
              secretKeyRef:
                name: "bpm-anomaly"
                key: user
                optional: true
          - name: BPM_ANOMALY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "bpm-anomaly"
                key: password
                optional: true
          - name: KCSOLUTION_CONTAINERS
            value: "containers"
          - name: KCSOLUTION_ORDERS
            value: "orders"
          - name: KCSOLUTION_REJECTED_ORDERS
            value: "rejected-orders"
          - name: KCSOLUTION_ALLOCATED_ORDERS
            value: "allocated-orders"
          - name: LOGGING_CONTAINER_MS_ROOT
            value: "INFO"
          - name: LOGGING_CONTAINER_MS_CONSUMER_CONFIG
            value: "ERROR"
          - name: LOGGING_CONTAINER_MS_PRODUCER_CONFIG
            value: "ERROR"
          - name: KAFKA_APIKEY
            valueFrom:
              secretKeyRef:
                name: "eventstreams-apikey"
                key: binding
          - name: POSTGRESQL_CA_PEM
            valueFrom:
              secretKeyRef:
                name: "postgresql-ca-pem"
                key: binding
          - name: POSTGRESQL_URL
            valueFrom:
              secretKeyRef:
                name: "postgresql-url"
                key: binding
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: "postgresql-user"
                key: binding
          - name: POSTGRESQL_PWD
            valueFrom:
              secretKeyRef:
                name: "postgresql-pwd"
                key: binding
        volumeMounts:
          - mountPath: "/config/resources/security/es-ssl"
            name: eventstreams-truststore
            readOnly: true
      volumes:
        - name: eventstreams-truststore
          secret:
            secretName: "eventstreams-truststore-jks"
