apiVersion: apps/v1
kind: Deployment
metadata:
  name: voyages-ms
spec:
  template:
    spec:
      containers:
      - name: voyagesms
        volumeMounts:
          - mountPath: /etc/ssl/certs/kcontainer
            name: es-pem-volume
            readOnly: true
